### ISSUE TITLE
LeagueSandbox

### ISSUE THREAD

**Issue by eddy5641** [horato/Minesweeper#1]
I know this is unrelated, but we are trying to switch to AGPL from the original GPL license, because it applies better to the project. As you were the original porter (porting it from c++ to c#) you are one of the most important people that need to sign the change. 

I have included a link to the project where you can create the pull request for the readme on github if you decide that you want to make the changes
https://github.com/LeagueSandbox/GameServer

Thank you,
eddy5641

**Comment by horato** [comment]
Done, thank you for letting me know ^^
